server:
  port: 80

spring:
  application:
    name: microservicecloud-user

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    #自定义服务名称信息
    instance-id: microservicecloud-user80
    #访问路径可以显示IP地址
    prefer-ip-address: true